// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrtdkuihhjzyanpozphd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydGRrdWloaGp6eWFucG96cGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODM2MTUsImV4cCI6MjA3MTg1OTYxNX0.CXIkb_QUqWUBk2W0ithZaltfBsZib5k927pXcBoyi30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});